cubosemantico = {
  	"int": {
			"int": {
				"+":"int",
				"-":"int",
				"*":"int",
				"/":"int",
				">":"bool",
				">=":"bool",
				"<=":"bool",
				"<":"bool",
				"=":"int",
				"==": "bool",
				"!=":"bool",
				"&&":"false",
				"||":"false",
				},
			"float": {
				"+":"false",
				"-":"false",
				"*":"false",
				"/":"false",
				">":"false",
				">=":"false",
				"<=":"false",
				"<":"false",
				"=":"false",
				"==": "false",
				"!=":"false",
				"&&":"false",
				"||":"false",
				},
			"string": {
				"+":"false",
				"-":"false",
				"*":"false",
				"/":"false",
				">":"false",
				">=":"false",
				"<=":"false",
				"<":"false",
				"=":"false",
				"==": "false",
				"!=":"false",
				"&&":"false",
				"||":"false",
				},
			"bool": {
				"+":"false",
				"-":"false",
				"*":"false",
				"/":"false",
				">":"false",
				">=":"false",
				"<=":"false",
				"<":"false",
				"=":"false",
				"==": "false",
				"!=":"false",
				"&&":"false",
				"||":"false",
				},
			},
		"float":{
			"int": {
				"+":"false",
				"-":"false",
				"*":"false",
				"/":"false",
				">":"false",
				">=":"false",
				"<=":"false",
				"<":"false",
				"=":"false",
				"==": "false",
				"!=":"false",
				"&&":"false",
				"||":"false",
				},
			"float": {
				"+":"float",
				"-":"float",
				"*":"float",
				"/":"float",
				">":"bool",
				">=":"bool",
				"<=":"bool",
				"<":"bool",
				"=":"float",
				"==": "bool",
				"!=":"bool",
				"&&":"false",
				"||":"false",
				},
			"string": {
				"+":"false",
				"-":"false",
				"*":"false",
				"/":"false",
				">":"false",
				">=":"false",
				"<=":"false",
				"<":"false",
				"=":"false",
				"==": "false",
				"!=":"false",
				"&&":"false",
				"||":"false",
				},
			"bool": {
				"+":"false",
				"-":"false",
				"*":"false",
				"/":"false",
				">":"false",
				">=":"false",
				"<=":"false",
				"<":"false",
				"=":"false",
				"==": "false",
				"!=":"false",
				"&&":"false",
				"||":"false",
				},
			},
		"string":{
			"int": {
				"+":"false",
				"-":"false",
				"*":"false",
				"/":"false",
				">":"false",
				">=":"false",
				"<=":"false",
				"<":"false",
				"=":"false",
				"==":"false",
				"!=":"false",
				"&&":"false",
				"||":"false",
				},
			"float": {
				"+":"false",
				"-":"false",
				"*":"false",
				"/":"false",
				">":"false",
				">=":"false",
				"<=":"false",
				"<":"false",
				"=":"false",
				"==": "false",
				"!=":"false",
				"&&":"false",
				"||":"false",
				},
			"string": {
				"+":"string",
				"-":"false",
				"*":"false",
				"/":"false",
				">":"false",
				">=":"false",
				"<=":"false",
				"<":"false",
				"=":"string",
				"==": "bool",
				"!=":"bool",
				"&&":"false",
				"||":"false",
				},
			"bool": {
				"+":"false",
				"-":"false",
				"*":"false",
				"/":"false",
				">":"false",
				">=":"false",
				"<=":"false",
				"<":"false",
				"=":"false",
				"==": "false",
				"!=":"false",
				"&&":"false",
				"||":"false",
				},
			},
		"bool":{
			"int": {
				"+":"false",
				"-":"false",
				"*":"false",
				"/":"false",
				">":"false",
				">=":"false",
				"<=":"false",
				"<":"false",
				"=":"false",
				"==": "false",
				"!=":"false",
				"&&":"false",
				"||":"false",
				},
			"float": {
				"+":"false",
				"-":"false",
				"*":"false",
				"/":"false",
				">":"false",
				">=":"false",
				"<=":"false",
				"<":"false",
				"=":"false",
				"==":"false",
				"!=":"false",
				"&&":"false",
				"||":"false",
				},
			"string": {
				"+":"false",
				"-":"false",
				"*":"false",
				"/":"false",
				">":"false",
				">=":"false",
				"<=":"false",
				"<":"false",
				"=":"false",
				"==":"false",
				"!=":"false",
				"&&":"false",
				"||":"false",
				},
			"bool": {
				"+":"false",
				"-":"false",
				"*":"false",
				"/":"false",
				">":"false",
				">=":"false",
				"<=":"false",
				"<":"false",
				"=":"bool",
				"==":"bool",
				"!=":"bool",
				"&&":"bool",
				"||":"bool",
				},
			},
		}
