cubosemantico = {
  	"int": {
			"int": {
				"+":"int",
				"-":"int",
				"*":"int",
				"/":"int",
				">":"bool",
				">=":"bool",
				"<=":"bool",
				"<":"bool",
				"=":"int",
				"==": "bool",
				"<>":"bool",
				"&&":"error",
				"||":"error",
				},
			"float": {
				"+":"error",
				"-":"error",
				"*":"error",
				"/":"error",
				">":"error",
				">=":"error",
				"<=":"error",
				"<":"error",
				"=":"error",
				"==": "error",
				"<>":"error",
				"&&":"error",
				"||":"error",
				},
			"string": {
				"+":"error",
				"-":"error",
				"*":"error",
				"/":"error",
				">":"error",
				">=":"error",
				"<=":"error",
				"<":"error",
				"=":"error",
				"==": "error",
				"<>":"error",
				"&&":"error",
				"||":"error",
				},
			"bool": {
				"+":"error",
				"-":"error",
				"*":"error",
				"/":"error",
				">":"error",
				">=":"error",
				"<=":"error",
				"<":"error",
				"=":"error",
				"==": "error",
				"<>":"error",
				"&&":"error",
				"||":"error",
				},
			},
		"float":{
			"int": {
				"+":"error",
				"-":"error",
				"*":"error",
				"/":"error",
				">":"error",
				">=":"error",
				"<=":"error",
				"<":"error",
				"=":"error",
				"==": "error",
				"<>":"error",
				"&&":"error",
				"||":"error",
				},
			"float": {
				"+":"float",
				"-":"float",
				"*":"float",
				"/":"float",
				">":"bool",
				">=":"bool",
				"<=":"bool",
				"<":"bool",
				"=":"float",
				"==": "bool",
				"<>":"bool",
				"&&":"error",
				"||":"error",
				},
			"string": {
				"+":"error",
				"-":"error",
				"*":"error",
				"/":"error",
				">":"error",
				">=":"error",
				"<=":"error",
				"<":"error",
				"=":"error",
				"==": "error",
				"<>":"error",
				"&&":"error",
				"||":"error",
				},
			"bool": {
				"+":"error",
				"-":"error",
				"*":"error",
				"/":"error",
				">":"error",
				">=":"error",
				"<=":"error",
				"<":"error",
				"=":"error",
				"==": "error",
				"<>":"error",
				"&&":"error",
				"||":"error",
				},
			},
		"string":{
			"int": {
				"+":"error",
				"-":"error",
				"*":"error",
				"/":"error",
				">":"error",
				">=":"error",
				"<=":"error",
				"<":"error",
				"=":"error",
				"==":"error",
				"<>":"error",
				"&&":"error",
				"||":"error",
				},
			"float": {
				"+":"error",
				"-":"error",
				"*":"error",
				"/":"error",
				">":"error",
				">=":"error",
				"<=":"error",
				"<":"error",
				"=":"error",
				"==": "error",
				"<>":"error",
				"&&":"error",
				"||":"error",
				},
			"string": {
				"+":"string",
				"-":"error",
				"*":"error",
				"/":"error",
				">":"error",
				">=":"error",
				"<=":"error",
				"<":"error",
				"=":"string",
				"==": "bool",
				"<>":"bool",
				"&&":"error",
				"||":"error",
				},
			"bool": {
				"+":"error",
				"-":"error",
				"*":"error",
				"/":"error",
				">":"error",
				">=":"error",
				"<=":"error",
				"<":"error",
				"=":"error",
				"==": "error",
				"<>":"error",
				"&&":"error",
				"||":"error",
				},
			},
		"bool":{
			"int": {
				"+":"error",
				"-":"error",
				"*":"error",
				"/":"error",
				">":"error",
				">=":"error",
				"<=":"error",
				"<":"error",
				"=":"error",
				"==": "error",
				"<>":"error",
				"&&":"error",
				"||":"error",
				},
			"float": {
				"+":"error",
				"-":"error",
				"*":"error",
				"/":"error",
				">":"error",
				">=":"error",
				"<=":"error",
				"<":"error",
				"=":"error",
				"==":"error",
				"<>":"error",
				"&&":"error",
				"||":"error",
				},
			"string": {
				"+":"error",
				"-":"error",
				"*":"error",
				"/":"error",
				">":"error",
				">=":"error",
				"<=":"error",
				"<":"error",
				"=":"error",
				"==":"error",
				"<>":"error",
				"&&":"error",
				"||":"error",
				},
			"bool": {
				"+":"error",
				"-":"error",
				"*":"error",
				"/":"error",
				">":"error",
				">=":"error",
				"<=":"error",
				"<":"error",
				"=":"bool",
				"==":"bool",
				"<>":"bool",
				"&&":"bool",
				"||":"bool",
				},
			},
		}
